# Read about configuration here: https://jekyllrb.com/docs/configuration/options/
title: L2Safety
description: A simplified view of Ethereum Layer 2 risks.
keywords: ethereum, eth, l2, risks
url: https://l2safety.info
permalink: pretty # Do not change this, it will break all links
timezone: America/New_York
markdown: kramdown
port: 4400
livereload: true

# Plugins
plugins:
  - jekyll-redirect-from # https://github.com/jekyll/jekyll-redirect-from
redirect_from: # jekyll-redirect-from
  json: false

# Navigation
nav_enabled: false

# Notification
enableNotification: false
notificationMsgId: 1 # must increment when creating a new message
notificationMsg: Join the <a href="">community</a>!
notificationExpiration: 3000000000 # epoch time in seconds

# Toast
enableToast: false
toastMsgId: 1 # must increment when creating a new message
toastTitle: 
toastMsg: 
toastLink:  # Optional, leave blank to omit
toastExpiration: 3000000000 # epoch time in seconds

# Assets
bootstrap_js: <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
bootstrap_css: <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">